services:
  database:
    container_name: database-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123*&
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - database-postgres:/var/lib/postgresql/data

volumes:
  database-postgres:
    driver: local